package com.soundapp.network.dto

data class SongDto(
    val wrapperType: Any?,
    val trackId: Any?,
    val artistName: Any?,
    val collectionName: Any?,
    val trackName: Any?,
    val collectionViewUrl: Any?,
    val trackViewUrl: Any?,
    val artistViewUrl: Any?,
    val previewUrl: Any?,
    val artworkUrl30: Any?,
    val artworkUrl60: Any?,
    val artworkUrl100: Any?,
    val collectionPrice: Any?,
    val trackPrice: Any?,
    val releaseDate: Any?,
    val collectionExplicitness: Any?,
    val trackExplicitness: Any?,
    val discCount: Any?,
    val discNumber: Any?,
    val trackCount: Any?,
    val trackNumber: Any?,
    val trackTimeMillis: Any?,
    val country: Any?,
    val currency: Any?,
    val primaryGenreName: Any?,
    val isStreamable: Any?
)